title: Christopher A. Johnson
url: "https://chrisajohnson.github.io"
theme: minima
minima:
  skin: dark
header_pages:
  - publications.md
  - contact.md
  - research:
      - range_lags.md
      - plant_pollinator.md
      - insect_responses.md
