title: Christopher A. Johnson
url: "https://chrisajohnson.github.io"
theme: minima
minima:
  skin: dark
  include:
    - assets/css/styles.css
header_pages:
  - research.md
  - publications.md
  - contact.md
